tosca_definitions_version: cloudify_dsl_1_4

imports:
  - cloudify/types/types.yaml
  - plugin:cloudify-azure-plugin
  - plugin:cloudify-utilities-plugin

inputs:

  deployment_id:
    description: Deployment ID of insfrastructure deployment
    display_label: Deployment ID
    type: string

dsl_definitions:

  azure_config: &azure_config
    subscription_id: { get_secret: azure_subscription_id }
    tenant_id: { get_secret: azure_tenant_id }
    client_id: { get_secret: azure_client_id }
    client_secret: { get_secret: azure_client_secret }

node_templates:

  resource_group:
    type: cloudify.azure.nodes.ResourceGroup
    properties:
      use_external_resource: true
      name: { get_capability: [ { get_input: deployment_id }, rg_id ] }
      location:  { get_capability: [ { get_input: deployment_id }, region_name ] }
      azure_config: *azure_config

  network_security_rule_1:
    type: cloudify.azure.nodes.network.NetworkSecurityRule
    properties:
      name: { concat: [ traefik1, { get_capability: [ { get_input: deployment_id }, security_group_id ] } ] }
      network_security_group_name: { get_capability: [ { get_input: deployment_id }, security_group_id ] }
      location: { get_capability: [ { get_input: deployment_id }, region_name ] }
      azure_config: *azure_config
      retry_after: 60
      resource_config:
        description: Traefik1
        protocol: Tcp
        sourcePortRange: '*'
        destinationPortRange: 80
        sourceAddressPrefix: '*'
        destinationAddressPrefix: '*'
        priority: 101
        access: Allow
        direction: Inbound
    relationships:
    - type: cloudify.azure.relationships.contained_in_resource_group
      target: resource_group

  network_security_rule_2:
    type: cloudify.azure.nodes.network.NetworkSecurityRule
    properties:
      name: { concat: [ traefik2, { get_capability: [ { get_input: deployment_id }, security_group_id ] } ] }
      network_security_group_name: { get_capability: [ { get_input: deployment_id }, security_group_id ] }
      location: { get_capability: [ { get_input: deployment_id }, region_name ] }
      azure_config: *azure_config
      retry_after: 60
      resource_config:
        description: Traefik2
        protocol: Tcp
        sourcePortRange: '*'
        destinationPortRange: 8080
        sourceAddressPrefix: '*'
        destinationAddressPrefix: '*'
        priority: 102
        access: Allow
        direction: Inbound
    relationships:
    - type: cloudify.azure.relationships.contained_in_resource_group
      target: resource_group