
- hosts: all
  become: true
  tasks:

    - name: Add the user 'vault'
      ansible.builtin.user:
        name: vault
        system: true
        home: /etc/vault.d
        shell: /bin/false

    - name: Creates directory
      file:
        path: "{{ item }}"
        state: directory
        owner: vault
        group: vault
      loop:
        - /mnt/vault/data
        - /opt/vault
        - /etc/vault.d

    - name: Download vault
      ansible.builtin.get_url:
        url: "{{ url_vault }}"
        dest: /opt/vault/vault.zip

    - name: Installing vault
      ansible.builtin.yum:
        name: unzip
        state: present

    - name: Unzipping
      shell: |
        unzip -d /opt/vault/ /opt/vault/vault.zip
        chown root:root /opt/vault/vault
        mv /opt/vault/vault /usr/local/bin 

    - name: Copy service properties
      ansible.builtin.copy:
        src: services/vault.service
        dest: /etc/systemd/system/vault.service

    - name: Copy service properties
      ansible.builtin.copy:
        src: config/vault.hcl
        dest: /etc/vault.d/vault.hcl

    - name: Daemon reload
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Ensure Vault service is started
      ansible.builtin.service:
        name: vault
        state: started
        enabled: true

    - name: Export seals to file
      shell: |
        export VAULT_ADDR="http://127.0.0.1:8200"
        vault operator init > /tmp/seals
      become_user: centos

    - name: read the intial Admin password
      command: cat /tmp/seals
      register: seals

    - name: "Set fact: output dictionary"
      set_fact:
        output_dict:
          seals: "{{ seals.stdout }}"

    - name: "Creates facts directory if it doesn't exist"
      file:
        path: "{{ lookup('ansible.builtin.env', 'ANSIBLE_FACT_PATH') }}"
        state: directory

    - name: "Insert custom fact file"
      copy:
        content: "{{ output_dict }}"
        dest: "{{ lookup('ansible.builtin.env', 'ANSIBLE_FACT_PATH') }}/custom.fact"
        mode: 0644