- hosts: all
  connection: local
  tasks:

    - name: Deleting resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group_name }}"
        state: absent
      register: rg
    - debug:
        var: rg