tosca_definitions_version: cloudify_dsl_1_4

imports:
  - cloudify/types/types.yaml
  - plugin:cloudify-azure-plugin
  - plugin:cloudify-utilities-plugin?version= >=1.22.1

inputs:

  rg_id:
    description: Resource group ID
    display_label: Resource Group ID
    type: string

  vpc_id:
    description: VPC id
    display_label: Vpc ID
    type: string

  security_group_id:
    description: SG id
    display_label: Security Group ID
    type: string

  region_name:
    display_label: Region Name
    type: string
    description: Your Azure Region
    default: eastus2
    constraints:
      - valid_values:
          - centralus
          - eastus
          - eastus2
          - westus
          - northcentralus
          - southcentralus
          - westcentralus
          - westus2
          - northeurope
          - westeurope
          - uksouth
          - ukwest
          - francecentral
          - francesouth
          - switzerlandnorth
          - switzerlandwest
          - germanynorth
          - germanywestcentral
          - norwaywest
          - norwayeast
          - canadacentral
          - canadaeast
          - brazilsouth
          - southafricanorth
          - southafricawest
          - eastasia
          - southeastasia
          - japanwest
          - japaneast
          - southindia
          - centralindia
          - westindia
          - koreacentral
          - koreasouth
          - uaecentral
          - uaenorth
          - australiaeast
          - australiasoutheast
          - australiacentral
          - australiacentral2

  retry_after:
    display_label: Retry After
    type: integer
    default: 60

dsl_definitions:

  azure_config: &azure_config
    subscription_id: { get_secret: azure_subscription_id }
    tenant_id: { get_secret: azure_tenant_id }
    client_id: { get_secret: azure_client_id }
    client_secret: { get_secret: azure_client_secret }

node_templates:

  resource_group:
    type: cloudify.nodes.azure.ResourceGroup
    properties:
      use_external_resource: true
      name: { get_input: rg_id }
      location: { get_input: region_name }
      azure_config: *azure_config

  network_security_group:
    type: cloudify.nodes.azure.network.NetworkSecurityGroup
    properties:
      use_external_resource: true
      name: { get_input: security_group_id }
      location: { get_input: region_name }
      azure_config: *azure_config
      retry_after: { get_input: retry_after }
      resource_config:
        securityRules:
          - name: Http
            properties:
              description: HTTP access
              protocol: Tcp
              sourcePortRange: '*'
              destinationPortRange: 8080
              sourceAddressPrefix: '*'
              destinationAddressPrefix: '*'
              priority: 101
              access: Allow
              direction: Inbound
    relationships:
      - type: cloudify.relationships.azure.contained_in_resource_group
        target: resource_group