- hosts: all
  become: true
  tasks:
    - name: Activate the epel-release repository
      ansible.builtin.yum:
        name: "{{ packages }}"
        state: present
        validate_certs: no
      vars:
        packages:
        - https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        - epel-release
    
    - name: Yum install postgres
      ansible.builtin.yum:
        name: postgresql11-server
        state: present
    
    - name: Init database
      ansible.builtin.command:
        argv:
        - /usr/pgsql-11/bin/postgresql-11-setup
        - initdb
        creates: /var/lib/pgsql/11/data/postgresql.conf
    
    - name: Copy hba configuration
      ansible.builtin.copy:
        src: config/pg_hba.conf
        dest: /var/lib/pgsql/11/data/pg_hba.conf

    - name: Copy postgresql configuration
      ansible.builtin.copy:
        src: config/postgresql.conf
        dest: /var/lib/pgsql/11/data/postgresql.conf
    
    - name: Ensure Postgres is started
      ansible.builtin.service:
        name: postgresql-11
        state: started
        enabled: true

    - name: Add home page with message
      ansible.builtin.template:
        src: templates/set-password.sql.j2
        dest: /tmp/set-password.sql

    - name: Init username
      shell: |
        psql -U postgres -f /tmp/set-password.sql
        exit 0

    - name: Ensure Postgres is enabled
      ansible.builtin.service:
        name: postgresql-11
        state: restarted
        enabled: true