tosca_definitions_version: cloudify_dsl_1_4

description: >
  This blueprint installs helm client, add repository to it and install
  chart(without values file and flags),using kubeconfig file content.
imports:
  - cloudify/types/types.yaml
  - plugin:cloudify-helm-plugin

inputs:

  repo_name:
    description: >
      Name of the repo to add.
    type: string

  chart_name:
    description: >
      Chart package name to deploy from repo.
  helm_installation_source:
    description: >
      Helm download link.
    type: string
    default: 'https://get.helm.sh/helm-v3.9.0-linux-amd64.tar.gz'

  repo_url:
    description: >
      URL of the repo to add. For example:
      https://kubernetes-charts.storage.googleapis.com/
    type: string

  kube_config:
    description: >
      kubeconfig path(on the manager vm).
    type: string


node_templates:

  helm_install:
    type: cloudify.nodes.helm.Binary
    properties:
      use_existing_resource: false
      installation_source: { get_input: helm_installation_source }

  repo:
    type: cloudify.nodes.helm.Repo
    properties:
      resource_config:
        name: { get_input: repo_name }
        repo_url: { get_input: repo_url }
    relationships:
      - target: helm_install
        type: cloudify.helm.relationships.run_on_host

  release:
    type: cloudify.nodes.helm.Release
    properties:
      client_config:
        configuration:
          manager_file_path: { get_input: kube_config }
      resource_config:
        name: "myrelease"
        chart: { concat: [ { get_input: repo_name },'/', { get_input: chart_name } ] }
    relationships:
      - target: helm_install
        type: cloudify.helm.relationships.run_on_host
      - target: repo
        type: cloudify.relationships.depends_on