tosca_definitions_version: cloudify_dsl_1_4

description: Cloudify helm-redis blueprint. Installs Postgresql Helm chart on top of Kubernetes cluster.

imports:
  - cloudify/types/types.yaml
  - plugin:cloudify-helm-plugin
  - plugin:cloudify-kubernetes-plugin

inputs:
  release_name:
    display_label: Release Name
    description: |
      Name of the helm release
    type: string
    default: example

  namespace:
    display_label: Namespace
    description: |
      Namespace to create resource
    type: string
    default: cert-manager

node_templates:

  helm_install:
    type: cloudify.nodes.helm.Binary
    properties:
      use_existing_resource: false
      installation_source: 'https://get.helm.sh/helm-v3.9.0-linux-amd64.tar.gz'

  repo:
    type: cloudify.nodes.helm.Repo
    properties:
      resource_config:
        name: jetstack
        repo_url: https://charts.jetstack.io
    relationships:
      - target: helm_install
        type: cloudify.helm.relationships.run_on_host

  namespace:
    type: cloudify.kubernetes.resources.Namespace
    properties:
      client_config:
        configuration:
          api_options:
            host: { get_environment_capability: kubernetes_cluster_host }
            api_key: { get_environment_capability: token }
            ssl_ca_cert: { get_environment_capability: ssl_ca_cert }
      definition:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: { get_input: namespace }

  release:
    type: cloudify.nodes.helm.Release
    properties:
      client_config:
        configuration:
          api_options:
            host: { get_environment_capability: kubernetes_cluster_host }
            api_key: { get_environment_capability: token }
            ssl_ca_cert: { get_environment_capability: ssl_ca_cert }
      resource_config:
        name: { get_input: release_name }
        chart: jetstack/cert-manager
        set_values:
          - name: installCRDs
            value: "true"
        flags:
          - name: namespace
            value: { get_input: namespace }
    relationships:
      - target: helm_install
        type: cloudify.helm.relationships.run_on_host
      - target: repo
        type: cloudify.relationships.depends_on
      - target: namespace
        type: cloudify.relationships.depends_on

labels:
  obj-type:
    values:
      - helm

capabilities:
  namespace:
    description: Namespace
    value: { get_input: namespace }
  service_name:
    description: Created service name
    value: { concat: [ { get_input: release_name }, "-cert-manager" ] }