- hosts: all
  become: true
  tasks:

    - name: Add prometheus user
      ansible.builtin.user:
        name: prometheus
        group: wheel
        state: present
        password: 'P@ssw0rd'

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: ~/Prometheus
        state: directory
        mode: '0755'
      become_user: prometheus

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: ~/Prometheus/node_exporter
        state: directory
        mode: '0755'
      become_user: prometheus

    - name: Download prometheus tar
      ansible.builtin.unarchive:
        src: https://github.com/prometheus/prometheus/releases/download/0.16.0/prometheus-0.16.0.linux-amd64.tar.gz
        dest: ~/Prometheus
        remote_src: yes
      become_user: prometheus

    - name: Download node exporter
      ansible.builtin.unarchive:
        src: https://github.com/prometheus/node_exporter/releases/download/0.11.0/node_exporter-0.11.0.linux-amd64.tar.gz
        dest: ~/Prometheus/node_exporter
        remote_src: yes
      become_user: prometheus
    
    - name: Copy node exporter service
      ansible.builtin.copy:
        src: services/node_exporter.service
        dest: /etc/systemd/system/node_exporter.service

    - name: Ensure Kafka started
      ansible.builtin.service:
        name: node_exporter
        state: started
        enabled: true
    
    - name: Copy node exporter service
      ansible.builtin.copy:
        src: config/prometheus.yaml
        dest: ~/Prometheus/prometheus-0.16.0.linux-amd64/prometheus.yml
      become_user: prometheus

    - name: Run prometheus
      shell: |
        cd ~/Prometheus/prometheus-0.16.0.linux-amd64
        nohup ./prometheus > prometheus.log 2>&1 &
      become_user: prometheus
