tosca_definitions_version: cloudify_dsl_1_5

description: Cloudify helm-bitbucket blueprint. Installs Bitbucket Helm chart on top of Kubernetes cluster.

imports:
  - cloudify/types/types.yaml
  - plugin:cloudify-helm-plugin
  - plugin:cloudify-kubernetes-plugin

inputs:
  release_name:
    display_label: Release Name
    description: |
      Name of the helm release
    type: string
    default: example

node_templates:
  helm_install:
    type: cloudify.nodes.helm.Binary
    properties:
      use_existing_resource: false
      installation_source: 'https://get.helm.sh/helm-v3.9.0-linux-amd64.tar.gz'

  repo:
    type: cloudify.nodes.helm.Repo
    properties:
      resource_config:
        name: common
        repo_url: https://atlassian.github.io/data-center-helm-charts
    relationships:
      - target: helm_install
        type: cloudify.helm.relationships.run_on_host

  secret:
    type: cloudify.kubernetes.resources.Secret
    properties:
      client_config:
        configuration:
          api_options:
            host: { get_environment_capability: kubernetes_cluster_host }
            api_key: { get_environment_capability: token }
            ssl_ca_cert: { get_environment_capability: ssl_ca_cert }
      use_external_resource: false
      definition:
        apiVersion: v1
        kind: Secret
        data: 
          password: "password"
        metadata:
          name: bitbucket
          namespace: default
        type: Opaque

  release:
    type: cloudify.nodes.helm.Release
    properties:
      client_config:
        configuration:
          api_options:
            host: { get_environment_capability: kubernetes_cluster_host }
            api_key: { get_environment_capability: token }
            ssl_ca_cert: { get_environment_capability: ssl_ca_cert }
      resource_config:
        name: { get_input: release_name }
        chart: atlassian-data-center/bitbucket
        values_file: values.yaml
        set_values:
          - name: bitbucket.service.type
            value: LoadBalancer
          - name: bitbucket.resources.container.requests.cpu
            value: 1
          - name: bitbucket.resources.jvm.maxHeap
            value: 1G
          - name: bitbucket.resources.jvm.minHeap
            value: 512m
          - name: ingress.https
            value: "false"
    relationships:
      - target: helm_install
        type: cloudify.helm.relationships.run_on_host
      - target: repo
        type: cloudify.relationships.depends_on

  svc:
    type: cloudify.kubernetes.resources.Service
    properties:
      client_config:
        configuration:
          api_options:
            host: { get_environment_capability: kubernetes_cluster_host }
            api_key: { get_environment_capability: token }
            ssl_ca_cert: { get_environment_capability: ssl_ca_cert }
      use_external_resource: true
      allow_node_redefinition: false
      definition:
        apiVersion: v1
        kind: Service
        metadata:
          name: { concat: [ { get_input: release_name } ] }
    relationships:
      - type: cloudify.relationships.depends_on
        target: release

labels:
  obj-type:
    values:
      - helm

capabilities:
  url:
    description: URL
    value: { concat: [ "http://", { get_attribute: [ svc, kubernetes, status, load_balancer, ingress, 0, ip ] } ] }