tosca_definitions_version: cloudify_dsl_1_5

description: >
  This blueprint installs helm client and add repository to it.
imports:
  - cloudify/types/types.yaml
  - plugin:cloudify-helm-plugin

inputs:
  repo_name:
    display_label: Repository Name
    description: >
      Name of the repository to add.
    type: string

  helm_installation_source:
    display_label: Helm Installation Source
    description: >
      Helm download link.
    type: string
    default: 'https://get.helm.sh/helm-v3.9.0-linux-amd64.tar.gz'
    constraints:
      - pattern: ^https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)$

  repo_url:
    display_label: Repository URL
    description: >
      URL of the repo to add. For example:
      https://kubernetes-charts.storage.googleapis.com/
    type: string

node_templates:

  helm_install:
    type: cloudify.nodes.helm.Binary
    properties:
      use_existing_resource: false
      installation_source: { get_input: helm_installation_source }

  repo:
    type: cloudify.nodes.helm.Repo
    properties:
      resource_config:
        name: { get_input: repo_name }
        repo_url: { get_input: repo_url }
    relationships:
      - target: helm_install
        type: cloudify.helm.relationships.run_on_host