- hosts: all
  become: true
  tasks:

    - name: Yum install MariaDB
      ansible.builtin.yum:
        name: mariadb-server
        state: present

    - name: Ensure MariaDB is started
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: true

    - name: Copy configuration file
      ansible.builtin.template:
        src: templates/mysql_secure_installation.sql.j2
        dest: /tmp/mysql_secure_installation.sql

    - name: Run scripts
      shell: |
        mysql < "/tmp/mysql_secure_installation.sql"
