tosca_definitions_version: cloudify_dsl_1_3

description: Cloudify helm-vault blueprint. Installs Vault Helm chart on top of Kubernetes cluster.

imports:
  - https://cloudify.co/spec/cloudify/6.2.0/types.yaml
  - plugin:cloudify-helm-plugin
  - plugin:cloudify-kubernetes-plugin

inputs:
  high_avability:
    display_label: High avability mode on/off
    description: |
      High avability mode on/off
    type: string
    default: "true"

  release_name:
    display_label: Name of the helm release
    description: |
      Name of the helm release
    type: string
    default: example

node_templates:
  helm_install:
    type: cloudify.nodes.helm.Binary
    properties:
      use_existing_resource: false
      installation_source: "https://get.helm.sh/helm-v3.7.2-linux-amd64.tar.gz"

  repo:
    type: cloudify.nodes.helm.Repo
    properties:
      resource_config:
        name: hashicorp
        repo_url: https://helm.releases.hashicorp.com
    relationships:
      - target: helm_install
        type: cloudify.helm.relationships.run_on_host

  release:
    type: cloudify.nodes.helm.Release
    properties:
      client_config:
        configuration:
          api_options:
            host:
              {
                concat:
                  [
                    "https://",
                    { get_environment_capability: kubernetes_cluster_host },
                  ],
              }
            api_key: { get_environment_capability: token }
            ssl_ca_cert: { get_environment_capability: ssl_ca_cert }
      resource_config:
        name: { get_input: release_name }
        chart: hashicorp/vault
        set_values:
          - name: server.ha.enabled
            value: { get_input: high_avability }
    relationships:
      - target: helm_install
        type: cloudify.helm.relationships.run_on_host
      - target: repo
        type: cloudify.relationships.depends_on

labels:
  obj-type:
    values:
      - helm
