tosca_definitions_version: cloudify_dsl_1_4

description: Cloudify helm-wordpress blueprint. Installs Wordpress Helm chart on top of Kubernetes cluster.

imports:
  - cloudify/types/types.yaml
  - plugin:cloudify-helm-plugin
  - plugin:cloudify-kubernetes-plugin

inputs:

  release_name:
    display_label: Name of the helm release
    description: |
      Name of the helm release
    type: string
    default: example

node_templates:

  secrets:
    type: cloudify.nodes.PasswordSecret
    properties:
      length: 12
      uppercase: 0
      lowercase: 7
      digits: 2
      symbols: 3
      use_secret_if_exists: false

  helm_install:
    type: cloudify.nodes.helm.Binary
    properties:
      use_existing_resource: false
      installation_source: 'https://get.helm.sh/helm-v3.7.2-linux-amd64.tar.gz'

  repo:
    type: cloudify.nodes.helm.Repo
    properties:
      resource_config:
        name: jenkins
        repo_url: https://charts.jenkins.io
    relationships:
      - target: helm_install
        type: cloudify.helm.relationships.run_on_host

  release:
    type: cloudify.nodes.helm.Release
    properties:
      client_config:
        configuration:
          api_options:
            host: { concat : [ "https://", { get_environment_capability: kubernetes_cluster_host } ] }
            api_key: { get_environment_capability: token }
            ssl_ca_cert: { get_environment_capability: ssl_ca_cert }
      resource_config:
        name: { get_input: release_name }
        chart: jenkins/jenkins
        values_file: values.yaml
        set_values:
          - name: controller.serviceType
            value: LoadBalancer
          - name: controller.adminPassword
            value: { get_attribute: [ secrets, password ] }
    relationships:
      - target: helm_install
        type: cloudify.helm.relationships.run_on_host
      - target: repo
        type: cloudify.relationships.depends_on
      - target: secrets
        type: cloudify.relationships.depends_on

  svc:
    type: cloudify.kubernetes.resources.Service
    properties:
      client_config:
        configuration:
          api_options:
            host: { concat : [ "https://", { get_environment_capability: kubernetes_cluster_host } ] }
            api_key: { get_environment_capability: token }
            ssl_ca_cert: { get_environment_capability: ssl_ca_cert }
      use_external_resource: true
      allow_node_redefinition: false
      definition:
        apiVersion: v1
        kind: Service
        metadata:
          name: {concat : [ { get_input: release_name }, -jenkins ] }
    relationships:
      - type: cloudify.relationships.depends_on
        target: release

labels:
  obj-type: 
    values: 
      - helm

capabilities:
  url:
    value: { concat: ["http://", { get_attribute: [svc, kubernetes, status, load_balancer, ingress, 0, ip ] }] } 
  password_jenkins:
    value: { get_attribute: [ secrets, password ] }
