tosca_definitions_version: cloudify_dsl_1_3

description: >
  This blueprint installs helm client, add repository to it and install
  chart(without values file and flags),using kubeconfig file content.
imports:
  - http://cloudify.co/spec/cloudify/5.0.5/types.yaml
  - plugin:cloudify-helm-plugin

inputs:

  repo_name:
    display_label: Name of the repo to add.
    description: >
      Name of the repo to add.
    type: string

  chart_name:
    display_label: Chart package name to deploy from repo.
    description: >
      Chart package name to deploy from repo.

  helm_installation_source:
    display_label: Helm download link.
    description: >
      Helm download link.
    type: string
    default: 'https://get.helm.sh/helm-v3.3.1-linux-amd64.tar.gz'

  repo_url:
    display_label: URL of the repo to add
    description: >
      URL of the repo to add. For example:
      https://kubernetes-charts.storage.googleapis.com/
    type: string

  release_name:
    display_label: Name of the created release
    description: >
      Name of the created release.
    type: string


node_templates:

  helm_install:
    type: cloudify.nodes.helm.Binary
    properties:
      use_existing_resource: false
      installation_source: { get_input: helm_installation_source }

  repo:
    type: cloudify.nodes.helm.Repo
    properties:
      resource_config:
        name: { get_input: repo_name }
        repo_url: { get_input: repo_url }
    relationships:
      - target: helm_install
        type: cloudify.helm.relationships.run_on_host

  release:
    type: cloudify.nodes.helm.Release
    properties:
      client_config:
        configuration:
          file_content: { get_secret: kube_config }
          api_options:
            api_key: { get_secret: kube_token }
      resource_config:
        name: { get_input: release_name }
        chart: { concat: [ { get_input: repo_name },'/', { get_input: chart_name } ] }
    relationships:
      - target: helm_install
        type: cloudify.helm.relationships.run_on_host
      - target: repo
        type: cloudify.relationships.depends_on