- hosts: all
  become: true
  tasks:
    - name: Install Erlang & RabbitMQ
      ansible.builtin.yum:
        name: "{{ packages }}"
        state: present
        validate_certs: no
      vars:
        packages:
        - epel-release
        - https://packages.erlang-solutions.com/erlang/rpm/centos/7/x86_64/esl-erlang_23.3.1-1~centos~7_amd64.rpm
        - https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.8.19/rabbitmq-server-3.8.19-1.el7.noarch.rpm

    - name: Start & Enable RabbitMQ service
      ansible.builtin.service:
        name: rabbitmq-server
        state: started
        enabled: true

    - name: Enable RabbitMQ Management
      ansible.builtin.command:
        argv:
        - rabbitmq-plugins
        - enable
        - rabbitmq_management

    - name: Disable Quest Account
      ansible.builtin.command:
        argv:
        - rabbitmqctl
        - delete_user
        - guest

    - name: Add Admin Account
      ansible.builtin.command:
        argv:
        - rabbitmqctl
        - add_user
        - admin
        - "{{ master_password }}"

    - name: Set admin as administrator
      ansible.builtin.command:
        argv:
        - rabbitmqctl
        - set_user_tags
        - admin
        - administrator

    - name: Set admin permissions
      shell: |
        rabbitmqctl set_permissions -p / admin ".*" ".*" ".*"