tosca_definitions_version: cloudify_dsl_1_4

description: Cloudify helm-drupal blueprint. Installs Drupal Helm chart on top of Kubernetes cluster.

imports:
  - cloudify/types/types.yaml
  - plugin:cloudify-helm-plugin
  - plugin:cloudify-kubernetes-plugin

inputs:
  username:
    display_label: Username
    description: |
      Username to be set in application
    type: string
    default: admin

  password:
    display_label: Password
    description: |
      Password to be set in application
    type: string
    default: Cl0ud1fY!

  email:
    display_label: Email
    description: |
      Email to be set in application
    type: string
    default: user@cloudify.co
    constraints:
      - pattern: ^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$

  release_name:
    display_label: Release Name
    description: |
      Name of the helm release
    type: string
    default: exampledrupal

node_templates:
  helm_install:
    type: cloudify.nodes.helm.Binary
    properties:
      use_existing_resource: false
      installation_source: 'https://get.helm.sh/helm-v3.9.0-linux-amd64.tar.gz'

  repo:
    type: cloudify.nodes.helm.Repo
    properties:
      resource_config:
        name: bitnami
        repo_url: https://charts.bitnami.com/bitnami
    relationships:
      - target: helm_install
        type: cloudify.helm.relationships.run_on_host

  release:
    type: cloudify.nodes.helm.Release
    properties:
      client_config:
        configuration:
          api_options:
            host: { get_environment_capability: kubernetes_cluster_host }
            api_key: { get_environment_capability: token }
            ssl_ca_cert: { get_environment_capability: ssl_ca_cert }
      resource_config:
        name: { get_input: release_name }
        chart: bitnami/drupal
        set_values:
          - name: drupalUsername
            value: { get_input: username }
          - name: drupalPassword
            value: { get_input: password }
          - name: drupalEmail
            value: { get_input: email }
    relationships:
      - target: helm_install
        type: cloudify.helm.relationships.run_on_host
      - target: repo
        type: cloudify.relationships.depends_on

  svc:
    type: cloudify.kubernetes.resources.Service
    properties:
      client_config:
        configuration:
          api_options:
            host: { get_environment_capability: kubernetes_cluster_host }
            api_key: { get_environment_capability: token }
            ssl_ca_cert: { get_environment_capability: ssl_ca_cert }
      use_external_resource: true
      allow_node_redefinition: false
      definition:
        apiVersion: v1
        kind: Service
        metadata:
          name: { get_input: release_name }
    relationships:
      - type: cloudify.relationships.depends_on
        target: release

labels:
  obj-type:
    values:
      - helm

capabilities:
  url:
    description: URL
    value: { concat: ["http://", { get_attribute: [svc, kubernetes, status, load_balancer, ingress, 0, hostname] }] }
  login_page:
    description: Login page URL
    value: { concat: ["http://", { get_attribute: [svc, kubernetes, status, load_balancer, ingress, 0, hostname] }, "/user/login"] }
