- hosts: all
  become: true
  tasks:
    - name: Setup MongoDB repo
      ansible.builtin.copy:
        src: repo/mongodb-org.repo
        dest: /etc/yum.repos.d/mongodb-org.repo
    
    - name: Activate the epel-release repository
      ansible.builtin.yum:
        name: mongodb-org
        state: present

    - name: Ensure Postgres is started
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: true

    - name: Copy create-user script
      ansible.builtin.template:
        src: templates/create-user.js.j2
        dest: /tmp/create-user.js

    - name: Copy set-admin-password script
      ansible.builtin.template:
        src: templates/set-admin-password.js.j2
        dest: /tmp/set-admin-password.js

    - name: Run scripts
      shell: |
        mongo < /tmp/create-user.js
        mongo < /tmp/set-admin-password.js
    
    - name: Listen on 0.0.0.0
      ansible.builtin.copy:
        src: config/mongod.conf
        dest: /etc/mongod.conf

    - name: Restart MongoDB
      ansible.builtin.service:
        name: mongod
        state: restarted
        enabled: true