tosca_definitions_version: cloudify_dsl_1_4

description: Cloudify Nginx blueprint. Deploys Nginx service with Ansible Cloduify plugin.

imports:
  - cloudify/types/types.yaml
  - plugin:cloudify-ansible-plugin

inputs:

  infra_name:
    type: string
    display_label: Name of the provider to deploy resources
    description: >
      Name of infrastructure blueprint to deploy.
    constraints:
      - valid_values:
          - azure
          - aws

  infra_archive:
    type: string
    display_label: URL for infra zip archive
    description: >
      URL of infra zip file.
    default: https://github.com/cloudify-community/cloudify-catalog/raw/6.4.0-build/tabs/other/multicloud/vm/vm.zip

  infra_exists:
    type: string
    display_label: Set if infra exists or not
    description: >
      Whether a getting started infrastructure blueprint has already been uploaded to the manager or not.
    default: false

  infra_deployment_id:
    type: string
    display_label: The infrastructure deployment id
    description: The blueprint name, the deployment name.
    default: { concat: [ 'infra-', { get_input: infra_name } ] }

  website_message:
    type: string
    display_label: A meesage to display on the NGINX home page
    description: A message to display on the home page of the deployed web server
    default: Welcome to NGINX, deployed by Cloudify

node_templates:

  infrastructure:
    type: cloudify.nodes.Component
    properties:
      resource_config:
        blueprint:
          blueprint_archive: { get_input: infra_archive }
          main_file_name: blueprint.yaml
          external_resource: { get_input: infra_exists }
        deployment:
          inputs:
            provider_name: { get_input: infra_name }

  secrurity_group_rules:
    type: cloudify.nodes.Component
    properties:
      resource_config:
        blueprint:
          blueprint_archive: security_group.zip
          main_file_name: { concat: [ { get_input: infra_name }, '.yaml' ] }
          external_resource: false
        deployment:
          inputs:
            rg_id: { get_attribute: [ infrastructure, capabilities, rg_id ] }
            vpc_id: { get_attribute: [ infrastructure, capabilities, vpc_id ] }
            security_group_id: { get_attribute: [ infrastructure, capabilities, security_group_id ] }
    relationships:
      - type: cloudify.relationships.depends_on
        target: infrastructure

  app:
    type: cloudify.nodes.ansible.Playbook
    interfaces:
      cloudify.interfaces.lifecycle:
        poststart: {}
    relationships:
      - type: cloudify.ansible.relationships.run_on_host
        target: infrastructure
        source_interfaces:
          cloudify.interfaces.relationship_lifecycle:
            establish:
              inputs:
                playbook_path: playbooks/install_nginx.yaml
                sources:
                  instances:
                    hosts:
                      instance:
                        ansible_host: { get_attribute: [ infrastructure, capabilities, endpoint ] }
                        ansible_user: { get_attribute: [ infrastructure, capabilities, user ] }
                        ansible_ssh_private_key_file: { get_attribute: [ infrastructure, capabilities, key_content ] }
                        ansible_become: true
                        ansible_ssh_common_args: -o StrictHostKeyChecking=no
                run_data:
                  message: { get_input: website_message }
outputs:
  nginx_endpoint:
    description: Nginx URL
    value: { concat: [ 'http://', { get_attribute: [ infrastructure, capabilities, endpoint ] }, ':80' ] }
