---

- hosts: all
  become: true
  vars:
    - oracle_password: "{{ ora_password }}"
  tasks:

     - name: Install EPEL package
       ignore_errors: yes
       become: true
       yum:
        state: present
        name:
          - yum-plugin-fastestmirror
          - epel-release


     - name: Add oracle repositories for dtrace
       yum_repository:
         name: EUK
         description: oracle EUK for dtrace
         file: oracle_EUK
         baseurl: http://yum.oracle.com/repo/OracleLinux/OL7/UEKR4/x86_64
         gpgcheck: no
         enabled: yes

     - name: updating the repo
       command: yum update -y

     - name: Install common software requirements
       ignore_errors: yes
       become: true
       yum:
        state: present
        name:
          - bc
          - wget
          - binutils
          - compat-libcap1
          - compat-libstdc++-33
          - dtrace-modules-headers
          - dtrace-modules-provider-headers
          - dtrace-utils
          - dtrace-utils-devel
          - dtrace-utils-testsuite
          - elfutils-libelf
          - elfutils-libelf-devel
          - fontconfig-devel
          - glibc
          - glibc-devel
          - ksh
          - libaio
          - libaio-devel
          - libdtrace-ctf-devel
          - libXrender
          - libXrender-devel
          - libX11
          - libXau
          - libXi
          - libXtst
          - libgcc
          - librdmacm-devel
          - libstdc++
          - libstdc++-devel
          - libxcb
          - make
          - net-tools # Clusterware
          - nfs-utils # ACFS
          - python # ACFS
          - python-configshell # ACFS
          - python-rtslib # ACFS
          - python-six # ACFS
          - targetcli # ACFS
          - smartmontools
          - sysstat
          - unzip
          - dos2unix

     - name: Add groups and user as required
       ignore_errors: yes
       shell: |
         groupadd -g 54321 oinstall
         groupadd -g 54322 dba
         groupadd -g 54323 oper
         groupadd -g 54324 backupdba
         groupadd -g 54325 dgdba
         groupadd -g 54326 kmdba
         groupadd -g 54327 asmdba
         groupadd -g 54328 asmoper
         groupadd -g 54329 asmadmin
         groupadd -g 54330 racdba
         useradd -u 54321 -g oinstall -G dba,oper oracle

     - name: change oracle password
       shell: echo '{{ oracle_password }}' |passwd --stdin oracle

     - name: create required swap
       shell: |
         mkdir /swap
         dd if=/dev/zero of=/swap/swapfile1 bs=1M count=4096
         mkswap  /swap/swapfile1
         chmod 600 /swap/swapfile1
         echo "/swap/swapfile1    swap   swap      defaults       0 0" >> /etc/fstab
         swapon -a
         free -m

     - name: create filesystem from allocated volume
       ignore_errors: yes
       shell: |
         part=/dev/xvdh
         /bin/echo -e "n\np\n1\n\n\nw" | fdisk $part
         newpart=$part"1"
         mkfs.ext4 $newpart
         mkdir /data
         mount $newpart /data
         chown oracle:oinstall /data
         echo "$newpart         /data  ext4      defaults       0 0" >> /etc/fstab

     - name: create db directories
       shell: |
         mkdir -p /data/u01/app/oracle/product/19.0.0/dbhome_1
         mkdir -p /data/u02/oradata
         chown -R oracle:oinstall /data/u01 /data/u02
         chmod -R 775 /data/u01 /data/u02
       
         

     - name: copying the binaries to the server
       copy:
         src: script/download.sh
         dest: /home/oracle
         owner: root
         group: root
         mode: 0755

     - name: run the download script from homeoracle to /data
       shell: |
         yum install dos2unix -y
         dos2unix /home/oracle/download.sh
         sh /home/oracle/download.sh

     - name: Set up the environment and unzip the binaries and Install Oracle binaries
       become_user: oracle
       shell: |
         export ORACLE_UNQNAME=cdb1
         export ORACLE_BASE=/data/u01/app/oracle
         export ORACLE_HOME=$ORACLE_BASE/product/19.0.0/dbhome_1
         export ORA_INVENTORY=/data/u01/app/oraInventory
         export ORACLE_SID=cdb1
         export PDB_NAME=pdb1
         export DATA_DIR=/data/u02/oradata
         export PATH=/usr/sbin:/usr/local/bin:$PATH
         export PATH=$ORACLE_HOME/bin:$PATH
         export LD_LIBRARY_PATH=$ORACLE_HOME/lib:/lib:/usr/lib
         export CLASSPATH=$ORACLE_HOME/jlib:$ORACLE_HOME/rdbms/jlib
         cd $ORACLE_HOME
         unzip /data/*.zip
         cd $ORACLE_HOME
         /bin/sh runInstaller -ignorePrereq -waitforcompletion -silent -responseFile ${ORACLE_HOME}/install/response/db_install.rsp oracle.install.option=INSTALL_DB_SWONLY ORACLE_HOSTNAME=${ORACLE_HOSTNAME} UNIX_GROUP_NAME=oinstall INVENTORY_LOCATION=${ORA_INVENTORY} SELECTED_LANGUAGES=en,en_GB ORACLE_HOME=${ORACLE_HOME} ORACLE_BASE=${ORACLE_BASE} oracle.install.db.InstallEdition=EE oracle.install.db.OSDBA_GROUP=dba oracle.install.db.OSBACKUPDBA_GROUP=dba oracle.install.db.OSDGDBA_GROUP=dba oracle.install.db.OSKMDBA_GROUP=dba oracle.install.db.OSRACDBA_GROUP=dba SECURITY_UPDATES_VIA_MYORACLESUPPORT=false DECLINE_SECURITY_UPDATES=true
       async: 600
       poll: 15
       ignore_errors: yes

     - name: Execute orainstroot.sh
       become_user: root
       shell: /bin/sh /data/u01/app/oraInventory/orainstRoot.sh


     - name: Execute root.sh
       become_user: root
       shell: /bin/sh /data/u01/app/oracle/product/19.0.0/dbhome_1/root.sh

     - name: adding environment variables to bash_profile
       become_user: oracle
       shell: |
         echo "export ORACLE_UNQNAME=cdb1" >> /home/oracle/.bash_profile
         echo "export ORACLE_BASE=/data/u01/app/oracle" >> /home/oracle/.bash_profile
         echo "export ORACLE_HOME=\$ORACLE_BASE/product/19.0.0/dbhome_1" >> /home/oracle/.bash_profile
         echo "export ORA_INVENTORY=/data/u01/app/oraInventory" >> /home/oracle/.bash_profile
         echo "export ORACLE_SID=cdb1" >> /home/oracle/.bash_profile
         echo "export PDB_NAME=pdb1" >> /home/oracle/.bash_profile
         echo "export DATA_DIR=/data/u02/oradata" >> /home/oracle/.bash_profile
         echo "export PATH=/usr/sbin:/usr/local/bin:\$PATH" >> /home/oracle/.bash_profile
         echo "export PATH=\$ORACLE_HOME/bin:\$PATH" >> /home/oracle/.bash_profile
         echo "export LD_LIBRARY_PATH=\$ORACLE_HOME/lib:/lib:/usr/lib" >> /home/oracle/.bash_profile
         echo "export CLASSPATH=\$ORACLE_HOME/jlib:\$ORACLE_HOME/rdbms/jlib" >> /home/oracle/.bash_profile
         echo "PATH=\$PATH:\$HOME/.local/bin:\$HOME/bin" >> /home/oracle/.bash_profile
         echo "export PATH" >> /home/oracle/.bash_profile


